name: isort

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install isort
        run: |
          python -m pip install -U isort
      - name: Check that imports are sorted
        run: |
          isort --check --profile=black --line-length=120 --diff g2p_mix
